name: my1studies
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  table_calendar: ^3.1.2
  intl: ^0.19.0
  url_launcher: ^6.2.5
  file_picker: ^8.0.0+1
  path_provider: ^2.1.4
  shared_preferences: ^2.2.2
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.4
  equatable: ^2.0.5
  dartz: ^0.10.1
  http: ^1.2.1
  google_mlkit_text_recognition: ^0.12.0
  image_picker: ^1.1.2
  share_plus: ^7.2.2
  uuid: ^4.5.1
  flutter_local_notifications: ^17.2.0
  sqflite: ^2.3.0
  timezone: ^0.9.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  
  assets:
    - assets/

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/app_icon.png"
    background_color: "#ffffff"
    theme_color: "#0175C2"
  windows:
    generate: true
    image_path: "assets/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/app_icon.png"
  image_path: "assets/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/app_icon.png"
